# Generated by Django 2.1.5 on 2019-03-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('uniform_num', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('mpg', models.IntegerField(blank=True, null=True)),
                ('ppg', models.IntegerField(blank=True, null=True)),
                ('rpg', models.IntegerField(blank=True, null=True)),
                ('apg', models.IntegerField(blank=True, null=True)),
                ('spg', models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True)),
                ('bpg', models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('color_id', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
    ]
